name: patchelf
version: '0.9+git'
version-script: |
    cat $SNAPCRAFT_STAGE/.version
summary: A small utility to modify the dynamic linker and RPATH of ELF executables
description: |
    PatchELF is a simple utility for modifying existing ELF executables and
    libraries. In particular, it can do the following,

    * Change the dynamic loader ("ELF interpreter") of executables.
    * Change the RPATH of executables and libraries.
    * Shrink the RPATH of executables and libraries.
    * Remove declared dependencies on dynamic libraries (DT_NEEDED
      entries).
    * Add a declared dependency on a dynamic library (DT_NEEDED).
    * Replace a declared dependency on a dynamic library with another one
     (DT_NEEDED).

grade: stable
confinement: classic

apps:
  patchelf:
    command: bin/patchelf

parts:
  patchelf:
    source: https://github.com/NixOS/patchelf.git
    prepare: |
        git describe --tags --dirty --always >> .version
    plugin: autotools
    install: install .version $SNAPCRAFT_STAGE/.version
